### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by WeatherMan5** [ufz-vislab/VtkFbxConverter#10]
Hi,
I would love to try the exporter for Paraview running on Windows
Is there any way to get dlls for Paraview 4+?

Many thanks
Ste

**Comment by bilke** [comment]
Thanks for your interest! I will send you the dlls next week!

**Comment by WeatherMan5** [comment]
Great!!
Thank you so much!

Ste

**Comment by bilke** [comment]
You can grab the DLL in the [latest release](https://github.com/ufz-vislab/VtkFbxConverter/releases/tag/1.0.1)!

**Comment by WeatherMan5** [comment]
Thanks!
I have manage to load it but it I try to export a vtk with vertex colours in fbx the output is somehow corrupted.
I don't get any colour and only part of the object is actually saved.

Am I missing something?

Many thanks!!!!
Ste

**Comment by bilke** [comment]
Vertex colors should be working. I have added an option to export to ascii mode. Maybe you can try that and have a look at the resulting file. Simply redownload the dll from the release page. Otherwise maybe you can send me your vtk file and I will have a look.
